<a href="https://colab.research.google.com/github/houstonsantos/DeepLearningPython/blob/master/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from keras.utils import np_utils
from keras.layers import Dense, Dropout
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential,model_from_json
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Rede Neural - Classificação Multiclesse
## HoldOut

In [3]:
# Importando bade de dados
base = pd.read_csv('dados/iris.csv')

# Separando feature e target
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values

In [14]:
base.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
#
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

In [5]:
# Dividindo entre treino e teste
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size = 0.25)

In [6]:
# Criando estrutura da rede neural
classificador = Sequential()
classificador.add(Dense(units = 4, activation = 'relu', input_dim = 4))
classificador.add(Dense(units = 4, activation = 'relu'))
classificador.add(Dense(units = 3, activation = 'softmax'))
classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
classificador.fit(previsores_treinamento, classe_treinamento, batch_size = 10, epochs = 1000)

ep - loss: 0.0312 - categorical_accuracy: 0.9754
Epoch 826/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.0351 - categorical_accuracy: 0.9869
Epoch 827/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0325 - categorical_accuracy: 0.9831
Epoch 828/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.0152 - categorical_accuracy: 0.9953
Epoch 829/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0233 - categorical_accuracy: 0.9895
Epoch 830/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0297 - categorical_accuracy: 0.9831
Epoch 831/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0199 - categorical_accuracy: 0.9914
Epoch 832/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.0478 - categorical_accuracy: 0.9668
Epoch 833/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.0387 - categorical_accuracy: 0.9869
Epoch 834/1000
12/12 [=================

In [7]:
# Accuracy usando keras
resultado = classificador.evaluate(previsores_teste, classe_teste)
resultado

2/2 [==============================] - 0s 2ms/step - loss: 0.1837 - categorical_accuracy: 0.9474


[0.1836850792169571, 0.9473684430122375]

In [8]:
# Realizando previsão do conjunto de teste
previsoes = classificador.predict(previsores_teste)
previsoes

array([[9.48433922e-07, 4.95502464e-02, 9.50448811e-01],
       [9.97679174e-01, 1.58820511e-03, 7.32646906e-04],
       [3.85369333e-07, 1.95912784e-03, 9.98040497e-01],
       [4.74925560e-04, 9.99163389e-01, 3.61790997e-04],
       [9.97679174e-01, 1.58820511e-03, 7.32646906e-04],
       [9.96394556e-06, 9.99907732e-01, 8.22856164e-05],
       [9.97679174e-01, 1.58820511e-03, 7.32646906e-04],
       [4.50363441e-05, 9.97989416e-01, 1.96555583e-03],
       [9.97679174e-01, 1.58820511e-03, 7.32646906e-04],
       [9.97679174e-01, 1.58820511e-03, 7.32646906e-04],
       [1.20323439e-05, 9.88641024e-01, 1.13470023e-02],
       [5.27292769e-08, 3.13281734e-03, 9.96867120e-01],
       [9.97679174e-01, 1.58820511e-03, 7.32646906e-04],
       [1.42117269e-08, 4.55572954e-05, 9.99954462e-01],
       [2.29946536e-07, 9.99979496e-01, 2.02560332e-05],
       [4.89847616e-06, 6.86114728e-02, 9.31383610e-01],
       [3.73418356e-04, 9.99296546e-01, 3.29959235e-04],
       [5.57998613e-11, 1.59117

In [9]:
previsoes = (previsoes > 0.5)
previsoes

array([[False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ T

### Métricas de Avaliação

In [10]:
# Tratando valores para matriz de confusão
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

In [11]:
# Matriz de confusão
matriz = confusion_matrix(previsoes2, classe_teste2)
matriz

array([[13,  0,  0],
       [ 0, 12,  0],
       [ 0,  2, 11]])

## Salvando e recuperando Rede Neural

In [24]:
# Criando objeto json com estrutura da rede neural
classificador_json = classificador.to_json()

# Sanvando em disco arquivo com rede neural
with open('ClassificadorIris.json', 'w') as json_file:
    json_file.write(classificador_json)

# Salvando os pesos da rede neural
classificador.save_weights('ClassificadorIris.h5')

In [25]:
# Nova instância para teste
novo = np.array([[5.1, 3.5, 1.4, 0.2]])

# Realizando previsão
previsao = classificador.predict(novo)
previsao = (previsao > 0.5)
previsao

array([[ True, False, False]])

In [28]:
# Carregando arquivo e lendo parâmetros da rede neural
arquivo = open('ClassificadorIris.json', 'r')
estrutura_rede = arquivo.read()
arquivo.close()

# Atribuindo estrutura e pessos da rede neural
classificador = model_from_json(estrutura_rede)
classificador.load_weights('ClassificadorIris.h5')

# Realizando previsão
previsao = classificador.predict(novo)
previsao = (previsao > 0.5)
previsao

array([[ True, False, False]])

# Rede Neural - Classificação Multiclasse
## Validação Cruzada com K-fold 

In [29]:
def criar_rede():
    classificador = Sequential()
    classificador.add(Dense(units = 4, activation = 'relu', input_dim = 4))
    # classificador.add(Dense(units = 4, activation = 'relu'))
    classificador.add(Dense(units = 3, activation = 'softmax'))
    classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
    
    return classificador

In [30]:
# Executando e treinando rede neural
classificador = KerasClassifier(build_fn = criar_rede, epochs = 1000, batch_size = 10)
resultados = cross_val_score(estimator = classificador, X = previsores, y = classe, cv = 10, scoring = 'accuracy')

Epoch 1/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.0905 - categorical_accuracy: 0.1641
Epoch 2/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.0691 - categorical_accuracy: 0.6240
Epoch 3/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.0410 - categorical_accuracy: 0.6109
Epoch 4/1000
14/14 [==============================] - 0s 1ms/step - loss: 1.0088 - categorical_accuracy: 0.5648
Epoch 5/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.9404 - categorical_accuracy: 0.6581
Epoch 6/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.8882 - categorical_accuracy: 0.6528
Epoch 7/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.8410 - categorical_accuracy: 0.6490
Epoch 8/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.8284 - categorical_accuracy: 0.6252
Epoch 9/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.8164 - categorical_accuracy:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


A saída de streaming foi truncada nas últimas 5000 linhas.
14/14 [==============================] - 0s 2ms/step - loss: 0.1091 - categorical_accuracy: 0.9526
Epoch 503/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0781 - categorical_accuracy: 0.9831
Epoch 504/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0700 - categorical_accuracy: 0.9859
Epoch 505/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0787 - categorical_accuracy: 0.9776
Epoch 506/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0599 - categorical_accuracy: 0.9838
Epoch 507/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0859 - categorical_accuracy: 0.9793
Epoch 508/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0719 - categorical_accuracy: 0.9797
Epoch 509/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.0712 - categorical_accuracy: 0.9794
Epoch 510/1000
14/14 [======================

In [31]:
# Média dos folds
media = resultados.mean()
media

0.9466666666666667

In [32]:
# Desvio padrão dos folds
desvio = resultados.std()
desvio

0.09333333333333332

# Rede Neural - Classificação Multiclesse
## Validação Cruzada com K-fold e GridSearchCV

In [33]:
# Criando função para rede neural
def criarRede(optimizer, loos, kernel_initializer, activation, neurons):
    # Criando estrutura da rede neural
    classificador = Sequential()
    classificador.add(Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer, input_dim = 4))
    classificador.add(Dropout(0.2))
    #classificador.add(Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer))
    #classificador.add(Dropout(0.2))
    classificador.add(Dense(units = 1, activation = 'softmax'))
    # Compilando rede neural
    classificador.compile(optimizer = optimizer, loss = loos, metrics = ['categorical_accuracy'])

    return classificador

In [34]:
# Build e parâmetros para treinamento da rede neural
classificador = KerasClassifier(build_fn = criarRede)

# Parâmetros para o GridSearchCV
parametros = {'batch_size': [10, 30],
              'epochs': [50, 100],
              'optimizer': ['adam', 'sgd'],
              'loos': ['binary_crossentropy', 'hinge'],
              'kernel_initializer': ['random_uniform', 'normal'],
              'activation': ['relu', 'tanh'],
              'neurons': [16, 8]}

In [35]:
# Parâmetros para o execução do GridSearchCV
grid_search = GridSearchCV(estimator = classificador, param_grid = parametros, scoring = 'accuracy', cv = 5)

In [36]:
# Executando treinamento e teste usando validação cruzada com 5 folds e GridSearchCV
grid_search = grid_search.fit(previsores, classe)

Epoch 1/50
12/12 [==============================] - 0s 2ms/step - loss: 0.7473 - categorical_accuracy: 1.0000
Epoch 2/50
12/12 [==============================] - 0s 2ms/step - loss: 0.3602 - categorical_accuracy: 1.0000
Epoch 3/50
12/12 [==============================] - 0s 2ms/step - loss: 0.0809 - categorical_accuracy: 1.0000
Epoch 4/50
12/12 [==============================] - 0s 1ms/step - loss: -0.1291 - categorical_accuracy: 1.0000
Epoch 5/50
12/12 [==============================] - 0s 2ms/step - loss: -0.3091 - categorical_accuracy: 1.0000
Epoch 6/50
12/12 [==============================] - 0s 1ms/step - loss: -0.5481 - categorical_accuracy: 1.0000
Epoch 7/50
12/12 [==============================] - 0s 1ms/step - loss: -0.5765 - categorical_accuracy: 1.0000
Epoch 8/50
12/12 [==============================] - 0s 1ms/step - loss: -0.8131 - categorical_accuracy: 1.0000
Epoch 9/50
12/12 [==============================] - 0s 1ms/step - loss: -1.0823 - categorical_accuracy: 1.0000
Epoc

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


A saída de streaming foi truncada nas últimas 5000 linhas.
4/4 [==============================] - 0s 3ms/step - loss: -3.7770 - categorical_accuracy: 1.0000
Epoch 64/100
4/4 [==============================] - 0s 3ms/step - loss: -4.3210 - categorical_accuracy: 1.0000
Epoch 65/100
4/4 [==============================] - 0s 2ms/step - loss: -4.0373 - categorical_accuracy: 1.0000
Epoch 66/100
4/4 [==============================] - 0s 8ms/step - loss: -4.1399 - categorical_accuracy: 1.0000
Epoch 67/100
4/4 [==============================] - 0s 4ms/step - loss: -4.7556 - categorical_accuracy: 1.0000
Epoch 68/100
4/4 [==============================] - 0s 4ms/step - loss: -3.8205 - categorical_accuracy: 1.0000
Epoch 69/100
4/4 [==============================] - 0s 5ms/step - loss: -4.2341 - categorical_accuracy: 1.0000
Epoch 70/100
4/4 [==============================] - 0s 4ms/step - loss: -4.3012 - categorical_accuracy: 1.0000
Epoch 71/100
4/4 [==============================] - 0s 4ms/step - 

In [37]:
# Melhores parâmetros encontrado pelo GridSearchCV
melhores_parametros = grid_search.best_params_
melhores_parametros

{'activation': 'relu',
 'batch_size': 10,
 'epochs': 50,
 'kernel_initializer': 'random_uniform',
 'loos': 'binary_crossentropy',
 'neurons': 16,
 'optimizer': 'adam'}

In [38]:
# Melhor precisão encontrada
melhor_precisao = grid_search.best_score_
melhor_precisao

0.3333333333333333